/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package devops;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }


    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        livre test=new livre("les fleurs du mal","Baudelaire");
        System.out.println(test.getAuteur());
        System.out.println(test.getTitre());

    }
}
